apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp-v2
spec:
  tls:
    - hosts:
      - v2.zhoubo.com
      secretName: tls-secret
  rules:
    - host: v2.zhoubo.com
      http:
        paths:
        - path: /
          backend:
            serviceName: myapp-v2-svc
            servicePort: 80