#服务器配置
server:
  port: 8080

#自定义配置
self:
  custom:
    config:
      sdkSecret: abc123
      port: ${server.port}

#spring配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.190:33306/imooc-springboot-learn?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: test@123
    #HikariCP配置
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  banner:
    location: classpath:banner/logo.txt
#    image:
#      location: classpath:banner/logo.jpg
#      pixelmode: TEXT

#MyBatis配置
mybatis:
  type-aliases-package: com.imooc.pojo  #数据库与实体类对应的包
  mapper-locations: classpath:mappers/*.xml #mapper映射文件

#通用mapper配置
mapper:
  mappers: com.imooc.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL

#分页帮助类配置
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true