server:
  port: 8080

self:
  custom:
    config:
      sdkSecret: abc123
      port: ${server.port}

spring:
  banner:
    location: classpath:banner/logo.txt
#    image:
#      location: classpath:banner/logo.jpg
#      pixelmode: TEXT