apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset-daemonset
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx-daemonset
  template:
    metadata:
      name: nginx-daemonset-template
      labels:
        app: nginx-daemonset
    spec:
      containers:
        - name: nginx-daemonset-container
          image: registry.cn-hangzhou.aliyuncs.com/zhoubo56/myapp:v1
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: ali-zhoubo