apiVersion: v1
kind: Service
metadata:
  name: init-c-myservice
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376

---

apiVersion: v1
kind: Service
metadata:
  name: init-c-mydb
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9377

