apiVersion: v1
kind: Pod
metadata:
  name: init-c-pod
  labels:
    app: init-c
spec:
  containers:
  - name: init-container
    image: registry.cn-hangzhou.aliyuncs.com/zhoubo56/busybox:v1
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  initContainers:
  - name: init-myservice
    image: registry.cn-hangzhou.aliyuncs.com/zhoubo56/busybox:v1
    command: ['sh', '-c', 'until nslookup init-c-myservice; do echo waiting for init-c-myservice; sleep 2; done;']
  - name: init-mydb
    image: registry.cn-hangzhou.aliyuncs.com/zhoubo56/busybox:v1
    command: ['sh', '-c', 'until nslookup init-c-mydb; do echo waiting for init-c-mydb; sleep 2; done;']  # until nc -vz mysql 3306;
  imagePullSecrets:
    - name: ali-zhoubo
