apiVersion: v1
kind: Service
metadata:
  name: nginx-statefulset-service
  labels:
    app: nginx-statefulset
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx-statefulset
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset-statefulset
spec:
  selector:
    matchLabels:
      app: nginx-statefulset # has to match .spec.template.metadata.labels
  serviceName: nginx-statefulset-service
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: nginx-statefulset # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-statefulset
        image: registry.cn-hangzhou.aliyuncs.com/zhoubo56/myapp:v1
        ports:
        - containerPort: 80
          name: web
      imagePullSecrets:
        - name: ali-zhoubo
