apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-pod
spec:
  containers:
    - name: empty-dir-myapp-container
      image: registry.cn-hangzhou.aliyuncs.com/zhoubo56/myapp:v1
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
      imagePullPolicy: IfNotPresent
    - name: empty-dir-busybox-container
      image: registry.cn-hangzhou.aliyuncs.com/zhoubo56/busybox:v1
      command: ['sh', '-c', 'touch /tmp/key; sleep 600;']
      volumeMounts:
        - mountPath: /tmp
          name: cache-volume
      imagePullPolicy: IfNotPresent 
  volumes:
    - name: cache-volume
      emptyDir: {}
  imagePullSecrets:
    - name: ali-zhoubo