apiVersion: v1
kind: Pod
metadata:
  name: host-path-pod
spec:
  containers:
    - name: host-path-myapp-container
      image: registry.cn-hangzhou.aliyuncs.com/zhoubo56/myapp:v1
      volumeMounts:
        - mountPath: /data
          name: data-volume
      imagePullPolicy: IfNotPresent
  volumes:
    - name: data-volume
      hostPath: 
        path: /data
        type: Directory
  imagePullSecrets:
    - name: ali-zhoubo