apiVersion: v1
kind: Pod
metadata:
  name: default-cpu-demo-3
  namespace: default-cpu-example
spec:
  containers:
  - name: default-cpu-demo-3-ctr
    image: registry.cn-hangzhou.aliyuncs.com/zhoubo56/myapp:v1
    resources:
      requests:
        cpu: "0.75"
  imagePullSecrets:
    - name: ali-zhoubo
