apiVersion: v1
kind: Pod
metadata:
  name: default-cpu-demo-2
  namespace: default-cpu-example
spec:
  containers:
  - name: default-cpu-demo-2-ctr
    image: registry.cn-hangzhou.aliyuncs.com/zhoubo56/myapp:v1
    resources:
      limits:
        cpu: "1"
  imagePullSecrets:
    - name: ali-zhoubo
