apiVersion: v1
kind: Pod
metadata:
  name: default-mem-demo-2
  namespace: default-mem-example
spec:
  containers:
  - name: default-mem-demo-2-ctr
    image: registry.cn-hangzhou.aliyuncs.com/zhoubo56/myapp:v1
    resources:
      limits:
        memory: "1Gi"
  imagePullSecrets: 
    - name: ali-zhoubo
