apiVersion: v1
kind: Pod
metadata: 
  name: default-mem-demo-3
  namespace: default-mem-example
spec: 
  containers: 
  - name: default-mem-demo-3-ctr
    image: registry.cn-hangzhou.aliyuncs.com/zhoubo56/myapp:v1
    resources: 
      requests: 
        memory: "128Mi"
  imagePullSecrets: 
    - name: ali-zhoubo
