apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotupdate-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotupdate
  template:
    metadata:
      name: hotupdate-template
      labels:
        app: hotupdate
    spec:
      containers:
        - name: hotupdate-container
          image: registry.cn-hangzhou.aliyuncs.com/zhoubo56/myapp:v1
          ports:
          - containerPort: 80
          volumeMounts:
          - name: log-volume
            mountPath: /etc/config
          imagePullPolicy: IfNotPresent
      volumes:
        - name: log-volume
          configMap:
            name: log-config
      imagePullSecrets:
        - name: ali-zhoubo