apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  containers:
    - name: volume-container
      image: registry.cn-hangzhou.aliyuncs.com/zhoubo56/busybox:v1
      command: ['sh', '-c', 'cat /etc/config/special.level']
      volumeMounts:
        - name: special-volume
          mountPath: /etc/config
      imagePullPolicy: IfNotPresent
  volumes:
    - name: special-volume
      configMap:
        name: special-config
  restartPolicy: Never
  imagePullSecrets:
    - name: ali-zhoubo