apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-path-pv-1
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: host-path
  hostPath:
    path: "/data/hostpath/01"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-path-pv-2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: host-path
  hostPath:
    path: "/data/hostpath/02"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: "host-path-pv-3"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: host-path
  hostPath:
    path: "/data/hostpath/03"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-path-pv-4
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: host-path
  hostPath:
    path: "/data/hostpath/04"