apiVersion: apps/v1
kind: Deployment
metadata:
  name: host-path-deployment-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: host-path-deployment
  template:
    metadata:
      name: host-path-deployment-template
      labels:
        app: host-path-deployment
    spec:
      containers:
        - name: host-path-deployment-container
          image: registry.cn-hangzhou.aliyuncs.com/zhoubo56/myapp:v1
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: ali-zhoubo
      nodeSelector:
        disktype: ssd
      volumes:
      - name: html
        persistentVolumeClaim:
          claimName: host-path-pvc-4