apiVersion: v1
kind: Service
metadata:
  name: nfs-statefulset-service
  namespace: default
  labels:
    app: nfs-statefulset
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
  selector:
    app: nfs-statefulset
  clusterIP: None

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs-statefulset-deployment
  namespace: default
spec:
  serviceName: nfs-statefulset
  replicas: 3
  selector:
    matchLabels:
      app: nfs-statefulset
  template:
    metadata:
      name: nfs-statefulset-template
      labels:
        app: nfs-statefulset
    spec:
      containers:
        - name: nfs-statefulset-container
          image: registry.cn-hangzhou.aliyuncs.com/zhoubo56/myapp:v1
          ports:
          - containerPort: 80
            name: web
          volumeMounts:
          - name: www
            mountPath: /usr/share/nginx/html
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: ali-zhoubo
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: ['ReadWriteOnce']
      storageClassName: 'nfs'
      resources:
        requests:
          storage: 1Gi
